# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_x64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_x64)
  raylib_config = debug_x64
  n_body_11_23_config = debug_x64

else ifeq ($(config),debug_x86)
  raylib_config = debug_x86
  n_body_11_23_config = debug_x86

else ifeq ($(config),debug_arm64)
  raylib_config = debug_arm64
  n_body_11_23_config = debug_arm64

else ifeq ($(config),release_x64)
  raylib_config = release_x64
  n_body_11_23_config = release_x64

else ifeq ($(config),release_x86)
  raylib_config = release_x86
  n_body_11_23_config = release_x86

else ifeq ($(config),release_arm64)
  raylib_config = release_arm64
  n_body_11_23_config = release_arm64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := raylib n-body_11_23

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

raylib:
ifneq (,$(raylib_config))
	@echo "==== Building raylib ($(raylib_config)) ===="
	@${MAKE} --no-print-directory -C _build -f raylib.make config=$(raylib_config)
endif

n-body_11_23: raylib
ifneq (,$(n_body_11_23_config))
	@echo "==== Building n-body_11_23 ($(n_body_11_23_config)) ===="
	@${MAKE} --no-print-directory -C _build -f n-body_11_23.make config=$(n_body_11_23_config)
endif

clean:
	@${MAKE} --no-print-directory -C _build -f raylib.make clean
	@${MAKE} --no-print-directory -C _build -f n-body_11_23.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_x64"
	@echo "  debug_x86"
	@echo "  debug_arm64"
	@echo "  release_x64"
	@echo "  release_x86"
	@echo "  release_arm64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   raylib"
	@echo "   n-body_11_23"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"